"""add group chat messages

Revision ID: 3ec3a499417c
Revises: e40d90cc4887
Create Date: 2026-04-16 15:47:33.486695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ec3a499417c'
down_revision: Union[str, Sequence[str], None] = 'e40d90cc4887'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_chat_messages_group_id'), 'group_chat_messages', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_chat_messages_id'), 'group_chat_messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_chat_messages_id'), table_name='group_chat_messages')
    op.drop_index(op.f('ix_group_chat_messages_group_id'), table_name='group_chat_messages')
    op.drop_table('group_chat_messages')
    # ### end Alembic commands ###
