"""add updated user columns

Revision ID: 50d8f6a8ec0c
Revises: 3ec3a499417c
Create Date: 2026-04-17 23:47:16.213946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50d8f6a8ec0c'
down_revision: Union[str, Sequence[str], None] = '3ec3a499417c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('badges', sa.Column('icon', sa.String(), server_default='', nullable=False))
    op.add_column('badges', sa.Column('label', sa.String(), server_default='Badge', nullable=False))
    op.add_column('badges', sa.Column('color', sa.String(), server_default='#000000', nullable=False))
    op.alter_column('badges', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('badges', 'icon_name')
    op.drop_column('badges', 'is_hidden')
    op.drop_column('badges', 'rarity')
    op.drop_column('badges', 'accent_color')
    op.drop_column('badges', 'name')
    op.add_column('users', sa.Column('xp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'xp')
    op.add_column('badges', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('badges', sa.Column('accent_color', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('badges', sa.Column('rarity', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('badges', sa.Column('is_hidden', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('badges', sa.Column('icon_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.alter_column('badges', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('badges', 'color')
    op.drop_column('badges', 'label')
    op.drop_column('badges', 'icon')
    # ### end Alembic commands ###
