"""add_challenges_system

Revision ID: e40d90cc4887
Revises: 5a3465e321cd
Create Date: 2026-04-16 12:18:59.843229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e40d90cc4887'
down_revision: Union[str, Sequence[str], None] = '5a3465e321cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('difficulty', sa.String(length=10), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('badge_id', sa.Integer(), nullable=True),
    sa.Column('target_count', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('action_filter', sa.JSON(), server_default='{}', nullable=True),
    sa.Column('icon', sa.String(length=30), nullable=False),
    sa.Column('accent_color', sa.String(length=7), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenges_id'), 'challenges', ['id'], unique=False)
    op.create_table('user_streaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_active_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('streak_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timezone_offset', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_streaks_id'), 'user_streaks', ['id'], unique=False)
    op.create_index(op.f('ix_user_streaks_user_id'), 'user_streaks', ['user_id'], unique=True)
    op.create_table('xp_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('level_after', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xp_transactions_id'), 'xp_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_xp_transactions_user_id'), 'xp_transactions', ['user_id'], unique=False)
    op.create_table('challenge_progress_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('action_ref_id', sa.Integer(), nullable=True),
    sa.Column('action_ref_type', sa.String(length=30), nullable=True),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_progress_log_dedup', 'challenge_progress_log', ['user_id', 'challenge_id', 'action_ref_type', 'action_ref_id'], unique=True, postgresql_where=sa.text('action_ref_id IS NOT NULL'))
    op.create_index(op.f('ix_challenge_progress_log_challenge_id'), 'challenge_progress_log', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_challenge_progress_log_id'), 'challenge_progress_log', ['id'], unique=False)
    op.create_index(op.f('ix_challenge_progress_log_user_id'), 'challenge_progress_log', ['user_id'], unique=False)
    op.create_table('user_challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_progress_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'challenge_id', name='uq_user_challenge')
    )
    op.create_index(op.f('ix_user_challenges_challenge_id'), 'user_challenges', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_user_challenges_id'), 'user_challenges', ['id'], unique=False)
    op.create_index(op.f('ix_user_challenges_user_id'), 'user_challenges', ['user_id'], unique=False)
    op.drop_table('spatial_ref_sys')
    op.drop_index(op.f('ix_groups_is_public'), table_name='groups')
    op.add_column('users', sa.Column('next_level_xp', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('total_xp_earned', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'total_xp_earned')
    op.drop_column('users', 'next_level_xp')
    op.create_index(op.f('ix_groups_is_public'), 'groups', ['is_public'], unique=False)
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.drop_index(op.f('ix_user_challenges_user_id'), table_name='user_challenges')
    op.drop_index(op.f('ix_user_challenges_id'), table_name='user_challenges')
    op.drop_index(op.f('ix_user_challenges_challenge_id'), table_name='user_challenges')
    op.drop_table('user_challenges')
    op.drop_index(op.f('ix_challenge_progress_log_user_id'), table_name='challenge_progress_log')
    op.drop_index(op.f('ix_challenge_progress_log_id'), table_name='challenge_progress_log')
    op.drop_index(op.f('ix_challenge_progress_log_challenge_id'), table_name='challenge_progress_log')
    op.drop_index('idx_progress_log_dedup', table_name='challenge_progress_log', postgresql_where=sa.text('action_ref_id IS NOT NULL'))
    op.drop_table('challenge_progress_log')
    op.drop_index(op.f('ix_xp_transactions_user_id'), table_name='xp_transactions')
    op.drop_index(op.f('ix_xp_transactions_id'), table_name='xp_transactions')
    op.drop_table('xp_transactions')
    op.drop_index(op.f('ix_user_streaks_user_id'), table_name='user_streaks')
    op.drop_index(op.f('ix_user_streaks_id'), table_name='user_streaks')
    op.drop_table('user_streaks')
    op.drop_index(op.f('ix_challenges_id'), table_name='challenges')
    op.drop_table('challenges')
    # ### end Alembic commands ###
